---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- name: sort
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
  label: sort
- type: tag_list
  name: Material
  label: Material
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/bamboo.md
- projects/chelsea-landmark.md
- projects/fantasy-1.md
- projects/ios-concept.md
- projects/jennie.md
- projects/la-fille-2.md
- projects/luna.md
- projects/n-a-1.md
- projects/n-a.md
- projects/skeleton-of-a-fantastic-animal-part.md
- projects/sky.md
